Models/ShopCart.cs
using Microsoft.AspNetCore.Components;
using Microsoft.EntityFrameworkCore;
using Shop.Data;
using System.Diagnostics;

namespace Shop.Models
{
    public class ShopCart
    {
        private readonly AppDBContent appDBContent;

        public ShopCart(AppDBContent appDBContent)
        {
            this.appDBContent = appDBContent;
        }

        public string Id { get; set; }
        public List<ShopCartItem> ShopCartItems { get; set; }

        public static ShopCart GetCart(IServiceProvider services)
        {
            ISession session = services.GetRequiredService<IHttpContextAccessor>()?.HttpContext.Session;
            var context = services.GetService<AppDBContent>();
            string shopCartId = session.GetString("CartId") ?? Guid.NewGuid().ToString();

            session.SetString("CartId", shopCartId);
            return new ShopCart(context) { Id = shopCartId};
        }

        
        public void AddToCart(Car car)
        {
            this.appDBContent.ShopCartItem.Add(new ShopCartItem
            {
                ShopCartId = Id,
                Car = car,
            });

            appDBContent.SaveChanges();
        }

        public void RemoveFromCart(int carId)
        {
            appDBContent.ShopCartItem.Remove(appDBContent.ShopCartItem.Where(x => x.ShopCartId == Id && x.Car.Id == carId).FirstOrDefault());
            appDBContent.SaveChanges();
        }

        public List<ShopCartItem> GetShopItems()
        {
            return appDBContent.ShopCartItem.Where(c => c.ShopCartId == Id).Include(s => s.Car).ToList();
        }
    }
}

ViewModels/ShopCartViewModel.cs
using Shop.Models;
namespace Shop.ViewModels
{
    public class ShopCartViewModel
    {
        public ShopCart ShopCart { get; set; }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data;
using Shop.Interfaces;
using Shop.Models;

namespace Shop.Controllers
{
    public class OrderController : Controller
    {
        private readonly AppDBContent appDBContent;
        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;

        public OrderController(AppDBContent appDBContent, IAllOrders allOrders, ShopCart shopCart)
        {
            this.allOrders = allOrders;
            this.shopCart = shopCart;
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public RedirectToActionResult Checkout(Order order)
        {
            allOrders.CreateOrder(order);
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data;
using Shop.Interfaces;
using Shop.Models;
using Shop.Repository;
using Shop.ViewModels;

namespace Shop.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IAllCars _carRepository;
        private readonly ShopCart _shopCart;
        private readonly AppDBContent _appDBContent;

        public ShopCartController(IAllCars carRepository, ShopCart shopCart, AppDBContent content)
        {
            _shopCart = shopCart;
            _carRepository = carRepository;
            _appDBContent = content;
        }

        public ViewResult Index()
        {
            var items = _shopCart.GetShopItems();
            _shopCart.ShopCartItems = items;
            _appDBContent.SaveChanges();
            var obj = new ShopCartViewModel() { ShopCart = _shopCart };
            return View(obj);
        }


        public RedirectToActionResult AddToCart(int id)
        {
            var item = _carRepository.Cars.FirstOrDefault(i => i.Id == id);
            if (item != null)
            {
                _shopCart.AddToCart(item);
            }

            return RedirectToAction("Index");
        }

        public RedirectToActionResult DeleteCar(int carId)
        {
            _shopCart.RemoveFromCart(carId);
            return RedirectToAction("Index");
        }
    }
}

Views/ShopCart/CarInCart.cshtml
@model Car
<div class="card mb-3">
    <div class="card-body">
        <div class="d-flex justify-content-between">
            <div class="d-flex flex-row align-items-center">
                <div>
                    <img src="@Model.Image" class="img-fluid rounded-3" alt="@Model.Name" style="width: 65px;">
                </div>
                <div class="ms-3">
                    <h5><ya-tr-span data-index="44-0" data-translated="true" data-source-lang="en" data-value="@Model.Name" data-type="trSpan" style="visibility: initial !important;">@Model.Name</ya-tr-span></h5>
                </div>
            </div>
            <div class="d-flex flex-row align-items-center">
                <div style="width: 80px;">
                    <h5 class="mb-0">@Model.Price</h5>
                </div>
                <a asp-controller="ShopCart" asp-action="DeleteCar" asp-route-carId="@Model.Id" style="color: #cecece;"><i class="fas fa-trash-alt">delete</i></a>
            </div>
        </div>
    </div>
</div>

                                    
                                

Views/ShopCart/Index.cshtml
@model ShopCartViewModel
<section class="pb-4">
    <div class="border rounded-5">

        <section class="w-100 p-4" style="background-color: #eee; border-radius: .5rem .5rem 0 0;">

            <div class="row">
                <div class="col">
                    <div class="card">
                        <div class="card-body p-4">

                            <div class="row">

                                <div class="col-lg-7">
                                    <h5 class="mb-3"><a href="/Cars/List" class="text-body"><i class="fas fa-long-arrow-alt-left me-2"></i><ya-tr-span data-index="27-0" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="Continue shopping" data-translation="Продолжайте делать покупки" data-ch="0" data-type="trSpan" style="visibility: initial !important;">Продолжайте делать покупки</ya-tr-span></a></h5>
                                    <hr>

                                    <div class="d-flex justify-content-between align-items-center mb-4">
                                        <div>
                                            <p class="mb-1"><ya-tr-span data-index="28-0" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="Shopping cart" data-translation="Корзина" data-ch="0" data-type="trSpan" style="visibility: initial !important;">Корзина</ya-tr-span></p>
                                            <p class="mb-0"><ya-tr-span data-index="29-0" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="Number of items in your shopping cart: @(Model.ShopCart.ShopCartItems.Count)" data-translation="Количество товаров в корзине: @(Model.ShopCart.ShopCartItems.Count)" data-ch="0" data-type="trSpan" style="visibility: initial !important;">Количество товаров в корзине: @(Model.ShopCart.ShopCartItems.Count)</ya-tr-span></p>
                                        </div>
                                    </div>
                                        @{
                                            foreach (ShopCartItem shopCartItem in Model.ShopCart.ShopCartItems)
                                            {
                                                @Html.Partial("CarInCart", shopCartItem.Car)
                                            }
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @{
                if (Model.ShopCart.ShopCartItems.Count > 0)
                {
                    <div><a class="btn btn-primary mt-2" asp-controller="Order" asp-action="Checkout">Pay</a></div>
                }
                else
                {
                    <div><a class="btn btn-primary mt-2 disabled" asp-controller="Order" asp-action="Checkout">Pay</a></div>
                }
            }
            
        </section>
      </div>
</section>